sudo: required
services:
  - docker

before_install:
  - docker build -t vansh912/docker-things-frontend -f Dockerfile.dev .

script: 
  - docker run vansh912/docker-things-frontend npm run test -- --coverage